const movieData = [
  { movieId: 1, genre: "drama" },
  { movieId: 2, genre: "fantasy" },
  { movieId: 3, genre: "horror" },
  { movieId: 4, genre: "action" },
  { movieId: 5, genre: "fantasy" },
  { movieId: 6, genre: "drama" },
  { movieId: 7, genre: "action" },
  { movieId: 8, genre: "action" },
  { movieId: 9, genre: "horror" },
  { movieId: 10, genre: "fantasy" },
  { movieId: 11, genre: "action" },
  { movieId: 12, genre: "horror" },
  { movieId: 13, genre: "fantasy" },
  { movieId: 14, genre: "fantasy" },
  { movieId: 15, genre: "fantasy" },
  { movieId: 16, genre: "horror" },
  { movieId: 17, genre: "drama" },
  { movieId: 18, genre: "fantasy" },
  { movieId: 19, genre: "drama" },
  { movieId: 20, genre: "horror" },
  { movieId: 21, genre: "sci-fi" },
  { movieId: 22, genre: "thriller" },
  { movieId: 23, genre: "sci-fi" },
  { movieId: 24, genre: "adventure" },
  { movieId: 25, genre: "fantasy" },
  { movieId: 26, genre: "horror" },
  { movieId: 27, genre: "drama" },
  { movieId: 28, genre: "sci-fi" },
  { movieId: 29, genre: "action" },
  { movieId: 30, genre: "fantasy" },
  { movieId: 31, genre: "thriller" },
  { movieId: 32, genre: "horror" },
  { movieId: 33, genre: "adventure" },
  { movieId: 34, genre: "fantasy" },
  { movieId: 35, genre: "thriller" },
  { movieId: 36, genre: "sci-fi" },
  { movieId: 37, genre: "action" },
  { movieId: 38, genre: "drama" },
  { movieId: 39, genre: "fantasy" },
  { movieId: 40, genre: "horror" },
];

export default movieData;
